module.exports = {
	"91": "Amazonas",
	"5": "Antioquia",
	"81": "Arauca",
	"8": "Atlántico",
	"13": "Bolívar",
	"15": "Boyacá",
	"17": "Caldas",
	"18": "Caquetá",
	"85": "Casanare",
	"19": "Cauca",
	"20": "Cesar",
	"27": "Chocó",
	"25": "Cundinamarca",
	"23": "Córdoba",
	"94": "Guainía",
	"95": "San José del Guaviare",
	"41": "Huila",
	"44": "La Guajira",
	"47": "Magdalena",
	"50": "Meta",
	"52": "Nariño",
	"54": "Norte de Santander",
	"86": "Putumayo",
	"63": "Quindío",
	"66": "Risaralda",
	"88": "San Andrés",
	"68": "Santander",
	"70": "Sucre",
	"73": "Tolima",
	"76": "Valle de Cauca",
	"97": "Vaupés",
	"99": "Vichada"
}